### ISSUE TITLE
Installing on SteamOS (Arch-like Linux distro)

### ISSUE THREAD

**Issue by UdderNonsense** [filips123/PWAsForFirefox#442] opened 2024-01-11 19:28 UTC
### Issue at hand:
I am toying around with my Valve Steam Deck (512GB LCD version) in desktop mode on SteamOS 3.5.7 with a KDE Plasma desktop.

I am able to install the extension in Firefox, but got stuck at the native-install step in the extension page. It defaulted to suggesting Debian-like installation steps, even though below it is the Arch-like installation steps. I have restarted the web browser multiple times.

After much futzing, I was able to use yay to install firefox-pwa-bin from AUR, and install the runtime through the command line. However, the web-browser GUI extension still does not progress.

### Steps to Reproduce

On a Steam Deck (or other system with Steam OS)

1. Install the extension as normal
3. Follow the download and install steps for Arch-Like distributions.
    Use the command ```$ steamos-readonly disable``` to ensure package managers can function properly
    I used ```$ yay -S firefox-pwa-bin``` - a prebuilt version of ```firefox-pwa```
4. Double check the web browser after installation completes.
6. Restart Firefox/the system as needed

Nothing is thrown or indicated by the extension page.

### Additional Information

I can achieve basic functionality using ```$ firefoxpwa site install <MANIFEST_URL>``` and successfully installed Excalidraw.

The debug console spits out ```Uncaught (in promise) Error: No such native application firefoxpwa```. However, this contradicts ```$ which firefoxpwa``` giving ```/usr/bin/firefoxpwa``` as it should.

I have noticed that ```/usr/libexec/firefoxpwa-connector``` does not exist. This may be the source of the issue, but I do not know how to rectify it.

* Operating system: SteamOS 3.5.7
* System architecture: amd64 (most likely)
* Desktop environment: KDE Plasma
* Installation method: 
* PWAsForFirefox extension version: 2.9.1
* PWAsForFirefox native version: 2.9.1
* PWAsForFirefox runtime version: 2.9.1
* Firefox version: 121.0

edit: I edited terminal inputs/outputs to include ```$``` prompts infront of commands. This is probably not kosher, but it's at least consistent within this post.

**Comment by filips123** [comment] 2024-01-11 20:11
> It defaulted to suggesting Debian-like installation steps, even though below it is the Arch-like installation steps.

The extension can only detect that you have Linux, but not which distro specifically, so it cannot automatically show you instructions for Arch. I decided to show Debian instructions by default as it's the most popular distro.

> I have noticed that `/usr/libexec/firefoxpwa-connector` does not exist.

This is normal, as the connector is located in `/usr/lib/firefoxpwa/firefoxpwa-connector` on Arch. Although this is probably not the problem, you can still check if that file actually exists, and if the manifest (`/usr/lib/mozilla/native-messaging-hosts/firefoxpwa.json`) points to it.

---

Is Firefox on SteamOS installed with Flatpak? If so, this is the problem, as Flatpak unfortunately does not support yet the Native Messaging API which is required for extension to communicate with the connector. If you can, please try downloading Firefox directly from Mozilla website and test if the extension works there.

If Firefox is installed natively, something else might be the problem, but I'm not sure yet...

**Comment by filips123** [comment] 2024-02-20 19:40
I will close this issue as it seems to be caused by Flatpak. Support for Flatpak is tracked in #142.

**Closed by filips123** 2024-02-20 19:40 UTC
Labels: bug, question
