### ISSUE TITLE
Site launch multiple tabs

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [filips123/PWAsForFirefox#391] opened 2023-09-03 15:38 UTC
Extend the site launch command to accept multiple webapps and start each of them in a seperate tab.
This way you can create a shortcut to launch mutliple PWAs in a single windows without dragging them together,

**Comment by filips123** [comment] 2023-09-14 17:33
Couldn't you just create a simple script that runs `firefoxpwa site launch` for each web app?

**Comment by Unkn0wn-MDCLXIV** [comment] 2023-09-15 15:15
That will launch them in two different windows instead.

**Comment by filips123** [comment] 2023-09-15 16:09
You want to launch multiple URLs, but they should all be merged inside a single PWA window? So, something like:

```
firefoxpwa site launch SITE-ID --url https://github.com/filips123/PWAsForFirefox/issues/391 --url https://github.com/ --url https://github.com/filips123/PWAsForFirefox
```

(note: this doesn't actually work)

**Comment by filips123** [comment] 2023-09-17 11:01
Also, a few more questions.

What to do when [the tabs mode](https://pwasforfirefox.filips.si/user-guide/browser/#show-browser-tabs-and-enable-using-multi-tabbed-web-apps) is disabled but you try to launch multiple URLs? Opening them as tabs won't work because tabs are hidden. Should it then open each URL in a separate web app window?

What to do when [the launch type](https://pwasforfirefox.filips.si/user-guide/browser/#changing-the-launch-type) is set to specific values and a window of the same web app is already opened?

- When the launch type is set to 0 (open in a new window, default), there shouldn't be any problem. It could just open a new window with all of the provided URLs as tabs.
- When it is set to 1 (open in a new tab), there also shouldn't be any problem. In that case, it could just use an existing window of that web app and open URLs as new tabs.
- The problem is when the launch type is set to 2 (replace the existing tab).
  - Should it replace the existing tab with the first provided URL and load all others as new tabs? This has the advantage that opening multiple URLs will still work, but it also means that the behaviour won't actually match what preference described, which might be confusing.
  - Should it replace the same existing tab with each URL, effectively loading only the last (or first) URL? This is what would match the name of the preference ("replace the existing tab") the most, but might still be confusing and will prevent loading multiple URLs if this option is enabled.
  - And what to do if there are already multiple tabs opened and you try to open multiple new URLs? Should it replace all of the existing tabs with requested URLs, and open the remaining URLs (if any) in new tabs?
- When the launch type is set to 3 (focus existing window), no URLs should open. This matches the current behaviour.

**Comment by filips123** [comment] 2023-09-17 16:58
After some consideration, I think that opening multiple URLs when the tabs mode is disabled or the launch type is set to replace the tab will be *unsupported* behaviour, at least in the initial version. There won't be anything preventing you from trying, but it might not work completely as expected. This will make the code much simpler than other options.

**Closed** 2023-09-22 19:22 UTC
Labels: enhancement
