### ISSUE TITLE
Linux Mobile Issue

### ISSUE THREAD

**Issue by ghost** [filips123/PWAsForFirefox#387] opened 2023-08-25 06:36 UTC
### Description

The menu that opens when you click (or tap in this case) on the add-on icon in the menu bar is too wide for my Pinephone's screen in vertical mode, which causes the menu to flicker until I click off of it or Firefox crashes.

### Steps to Reproduce

1. Be running Firefox ESR with a small screen.
2. Click on the add-on icon in the menu.

### Additional Information

This is related to a bug in Firefox itself where it has troubles with drawing menus if they're too large for the screen. I know that this is probably outside of the scope of the project, but figured I should report it anyway in case other Linux mobile users take an interest. PWA support options are limited at the moment.

### Environment

* Operating system: Mobian (Mobile Debian) Bookworm
* System architecture: aarch64/arm64
* Desktop environment: Phosh
* Installation method: DEB
* PWAsForFirefox extension version: 2.7.3
* PWAsForFirefox native version: 2.7.3
* PWAsForFirefox runtime version: 102.14.0esr
* Firefox version: 102.14.0esr

**Comment by filips123** [comment] 2023-08-26 17:09
If this is a Firefox bug with addon popups, I probably can't fix this. Popups can only slightly control their size, but even then, I don't know if I can configure and design it so it can fit on a phone screen. And because proper Linux phones are unfortunately quite rare, I also cannot easily test this.

A partial workaround is to open the popup in a separate full tab (`moz-extension://7cfc54ca-f6f9-4246-98f0-b83000f4ce88/sites/manage.html`). This way, the content will probably fit better, but installing sites won't work.

I plan to rewrite the extension soon™, so then I will try to design the UI so it works better on a small screen. Hopefully, Firefox will also fix that bug with flickering in the future (and limit the popup size to the screen I guess).

**Comment by qstambaugh** [comment] 2023-08-27 20:56
On Sat, 2023-08-26 at 10:09 -0700, Filip Š wrote:
> If this is a Firefox bug with addon popups, I probably can't fix
> this. Popups can only slightly control their size, but even then, I
> don't know if I can configure and design it so it can fit on a phone
> screen. And because proper Linux phones are unfortunately quite rare,
> I also cannot easily test this.
> 
> A partial workaround is to open the popup in a separate full tab
> (`moz-extension://7cfc54ca-f6f9-4246-98f0-
> b83000f4ce88/sites/manage.html`). This way, the content will probably
> fit better, but installing sites won't work.
> 
> I plan to rewrite the extension soon™, so then I will try to design
> the UI so it works better on a small screen. Hopefully, Firefox will
> also fix that bug with flickering in the future (and limit the popup
> size to the screen I guess).
> 
I have a ticket open with Mozilla about the issue. From what I can
find, it's an issue with how GTK is implemented in Firefox. I didn't
think it'd be an issue you could really fix. I opened the report more
so other Linux mobile users would be able to find the current state of
trying to use Firefox for PWAs if they search. Just taking mobile into
account when you redesign the UI is more than enough, thank you!

**Comment by filips123** [comment] 2024-09-13 17:41
I will close this issue as it is caused by Firefox so I can't do much. At some point, I will also rewrite the extension and try to improve the layout on small screens.

**Closed by filips123** 2024-09-13 17:41 UTC
Labels: bug
