### ISSUE TITLE
Arch Linux firefox package does not turn into PWA

### ISSUE THREAD

**Issue by Megver83** [filips123/PWAsForFirefox#181] opened 2022-07-20 06:22 UTC
### Description

I want to use the firefox distribution of Arch Linux, so I followed the steps of manual installation from package manager and when launching webapps, they look like this (Instagram webapp):

![ff-arch](https://user-images.githubusercontent.com/22277674/179909561-cf7eabc7-800b-46a6-8ddd-b6201be10fe7.png)

Instead of (this is using the portable upstream firefox):
 
![firefox](https://user-images.githubusercontent.com/22277674/179909691-590ad1e5-87f8-411a-a1a5-6399e9a12f2a.png)

The Arch firefox gets kinda the look and window size of the webapp, but looks like the heavy modifications don't get injected. Also, there is no "Progressive Web App" section in the settings.

### Steps to Reproduce

1. Copy `/usr/lib/firefox` into `~/.local/share/firefoxpwa/runtime`
2. Create a webapp
3. Launch it

### Environment

* Operating system: Arch Linux
* System architecture: x86_64
* Desktop environment: KDE Plasma 5 
* Installation method: AUR 
* PWAsForFirefox extension version: 1.4.2
* PWAsForFirefox native version: 1.4.2
* Firefox version: 102.0.1

**Comment by filips123** [comment] 2022-07-29 09:21
Does it work if you enable "Always patch runtime and profile" in the extension settings and then re-launch PWA?

**Comment by Megver83** [comment] 2022-07-29 18:46
Just did it. Nothing changed.

**Comment by spfanning** [comment] 2022-07-30 01:13
You wouldn't happen to be symlinking anything in the runtime would you?

**Comment by filips123** [comment] 2022-07-30 11:27
Maybe there are some problems with permissions? You can try to manually copy files from [`/usr/share/firefoxpwa/userchrome/runtime/`](https://github.com/filips123/PWAsForFirefox/tree/main/native/userchrome/runtime) (just contents of that folder). to `~/.local/share/firefoxpwa/runtime`.

Also, can you check logs before that as described [here in step 4](https://github.com/filips123/PWAsForFirefox/wiki/Troubleshooting) to see if they contain "Patching the runtime"?

**Comment by filips123** [comment] 2022-08-04 20:11
I tried to reproduce this on Arch with KDE Plasma (inside VM, installed using `archinstall`), but it works fine for me, so I don't know what could cause this for you. I think those errors in logs are also just some random things from Firefox.

**Comment by pklapperich** [comment] 2023-08-10 13:29
> this is using the portable upstream firefox

What does this mean? How do you have firefox installed (the main one)?

>1. Copy `/usr/lib/firefox` into `~/.local/share/firefoxpwa/runtime`

Can you share the exact command you used to copy? I used

```
$ rsync -r /usr/lib/firefox/ ~/.local/share/firefoxpwa/runtime/
skipping non-regular file "firefox-bin"
$
```
and everything worked for me:
![Screenshot_2023-08-10_08-50-55](https://github.com/filips123/PWAsForFirefox/assets/12666157/5bb8d27d-b874-4440-adf7-a5b1f008207d)

I'm using XFCE4

My guess would be _either_ something didn't copy right in your "step 1" _or_ there's a problem specific to the "portable firefox from upstream" that you're using. The only "portable firefox" I'm aware of is a Windows application (*.exe).

-----

In my setup I installed Firefox from the main repositories (`pacman -S firefox`) and I installed the [firefox-pwa aur package](https://aur.archlinux.org/packages/firefox-pwa). I haven't needed to use the "always patch" configuration option.

>1. Copy `/usr/lib/firefox` into `~/.local/share/firefoxpwa/runtime`

If you install the `firefox-pwa` package from AUR, then you don't need to do this. You can just click the button to install the runtime:
![Screenshot_2023-08-10_08-48-23](https://github.com/filips123/PWAsForFirefox/assets/12666157/f0141cde-4bb6-4b3d-af90-597be131be3a)

For what it's worth, I had problems when I first set up PWA back in Dec and followed the manual instructions under "Advanced Options" on that setup screen and I resolved it by deleting `~/.local/share/firefoxpwa/runtime/` and just clicking the button to install the runtime. But using rsync as above worked today with a fresh archlinux user profile.  It might be I ran into the same issue, but it's since been resolved?

**Comment by filips123** [comment] 2024-01-24 16:46
Does anyone still have this issue? If not, I will close this issue soon because I couldn't reproduce it and it doesn't seem to affect many users.

**Closed** 2024-02-20 14:44 UTC
Labels: bug, help wanted, could not reproduce
