### ISSUE TITLE
No Install Button in Install Menu

### ISSUE THREAD

**Issue by sethb124** [filips123/PWAsForFirefox#503] opened 2024-05-19 21:48 UTC
### Description

When clicking the 'install this site' button, there's no button to install the site on the menu that pops us. I can install sites using the CLI just fine. I tried doing the troubleshooting steps, but it doesn't produce any logs or errors anywhere. I normally use Firefox Nightly with lots of extensions, but it didn't work on a clean install of regular Firefox either.

### Steps to Reproduce

Click 'install this site' button on address bar.

### Additional Information

Here's what the install menu looks like, scrolled all the way down:

![Screenshot of install menu](https://github.com/filips123/PWAsForFirefox/assets/75157593/35bbe0fc-207f-4a6e-be81-b9147d86fb81)

### Environment

* Operating system: EndeavourOS (Arch-based)
* System architecture: x86_64
* Desktop environment: KDE Plasma 6
* Installation method: AUR (Tried both source and binary versions)
* PWAsForFirefox extension version: 2.12.0
* PWAsForFirefox native version: 2.12.0
* PWAsForFirefox runtime version: 126
* Firefox version: 126

**Comment by sethb124** [comment] 2024-05-19 21:59
I was able to get it working just fine on both Windows 10 and Linux Mint, so maybe this is an AUR problem.

**Comment by filips123** [comment] 2024-05-23 18:08
This is probably caused by some scaling issues. Issue #230 is similar.

**Comment by sethb124** [comment] 2024-05-23 18:15
> This is probably caused by some scaling issues. Issue #230 is similar.

You're exactly correct. Scaling my display down to 100% makes the install button appear. Thank you.

**Comment by filips123** [comment] 2024-05-23 18:50
Good to see that you were able to fix this, so I'll close this issue. In the future, I will probably also rewrite the extension and try to fix the original issue with scaling.

**Closed by filips123** 2024-05-23 18:50 UTC
Labels: bug
