### ISSUE TITLE
Multilingualize the extension

### ISSUE THREAD

**Issue by surapunoyousei** [filips123/PWAsForFirefox#340] opened 2023-05-19 10:01 UTC
With permission, I would like to make this extension multilingual.

 I am creating a Firefox derivative browser and wanted to support multilingualization of this addon as many users use this addon.

In some cases, I would like to manipulate the native implementation side as well.

**Comment by filips123** [comment] 2023-05-19 12:23
That would be nice. Do you already have any specific plans for how to do this?

I have already thought about internationalization/localization in the past. I haven't done anything yet, but here are some of my ideas:

* **[Extension](https://github.com/filips123/PWAsForFirefox/tree/main/extension):** WebExtensions support some [internationalization APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization), so it might be good to use that. However, most of the strings are currently hard-coded inside HTML files, so I'm not sure how to handle them properly. It seems there are some libraries for this ([one](https://github.com/erosman/HTML-Internationalization), [another](https://github.com/piroor/webextensions-lib-l10n)), so something like this can probably be used. Another thing to consider is that I will probably rewrite the extension to use a proper JS/TS framework (probably Vue or Svelte, but I haven't decided yet) in the future, because handling everything without a framework has become quite annoying.

* **[UserChrome](https://github.com/filips123/PWAsForFirefox/tree/main/native/userchrome) (widgets and other stuff in the app browser):** This can use [Fluent (FTL)](https://projectfluent.org/) localization system, as most of the normal Firefox UI already does. This shouldn't be that hard and I might try this myself in the future, as Fluent is already built into Firefox.

* **[Native](https://github.com/filips123/PWAsForFirefox/tree/main/native) (console program and connector):** I think localization is not needed and worth here, as it doesn't actually have an interface that most users will face. For the console part, I think that most users that use it (advanced users that know how to use the console) already know English and expect console programs to be in English. For the connector, the only relevant strings are error messages, which cannot easily be translated, and I also think that error messages should be kept untranslated (also in the extension), because this makes searching and troubleshooting easier.

For managing all translations, I think that [Crowdin](https://crowdin.com/) can be used because it supports both Fluent and WebExtensions format, has some free plans for open source projects, and I already started some testing there some time ago.

**Comment by surapunoyousei** [comment] 2023-05-19 12:39
I have experience with extensions and Firefox Runtime, so I can help.

I am a developer of the Floorp (https://github.com/Floorp-Projects/Floorp) browser, so I have experience with Fluent. I have mastered how to call it, but I need to work on registering .ftl files with userChromeJS.

I do not intend to integrate this add-on into my browser.

I have never used Crowdin and would like to register my native Japanese.

This will take some time. I will create a draft in PR as I proceed little by little. I will let you know when it is completed.

**Comment by surapunoyousei** [comment] 2023-05-19 12:45
I forgot to say

How do you debug extensions and runtime's JS.

**Comment by surapunoyousei** [comment] 2023-05-19 13:23
OK

**Comment by surapunoyousei** [comment] 2023-05-20 12:59
in preparation
![image](https://github.com/filips123/PWAsForFirefox/assets/73892113/e282bfa0-65f0-4726-978f-ad4bdc8c8e90)

**Comment by filips123** [comment] 2024-01-06 14:54
I'm sorry that this took such a long time. There were some complications that took a lot more time than I expected, and I also didn't have much free time to do this. But the localization, at least for the extension, is finally ready!

As the built-in WebExtensions localization system has some problems (lack of support for HTML translations, no support for pluralization, inability to change the language, etc.), I initially wanted to wait with localization until I rewrite the extension with a better framework. However, it turned out that this would take a lot of work and time, so this isn't ready yet. I still had to rewrite some things to support some features that the normal WebExtensions localization does not support, for example, pluralization and changing of the current language. The new system is mostly compatible with the standard one, but there are a few differences. There may still be some issues with the localization system, and I will probably fix them at some point when rewriting the extension.

I also changed message keys and some messages so they are a bit more consistent and can be translated more easily. Most of your existing Japanese translations have also been updated to the new message keys. However, in that time, some new messages were added which are currently still untranslated. You can translate them [on Crowdin](https://crowdin.com/project/firefoxpwa/ja).

For the UserChrome localization, I found a way to load Fluent files dynamically. It's still not ready yet, but I hope I will be able to implement it.

**Comment by surapunoyousei** [comment] 2024-01-06 14:58
No need for you to apologize at the all.

I think you developed too enough & so many efforts.

PWAsForFirefox to be localized is a benefit to many Firefox users. Excellent!

BTW, I was able to implement PWAs in Floorp, the browser I am developing! Cheers to PWAsForFirefox!

**Comment by filips123** [comment] 2024-01-07 17:40
I also made some progress on the UserChrome part. Almost everything is finished (widgets, preferences and other messages can be translated), apart from the Crowdin integration, but there is one critical problem...

File sources are registered in [`boot.jsm`](https://github.com/filips123/PWAsForFirefox/blob/a9b668b9a280398f241f4ecbcb69a1af55647ec8/native/userchrome/profile/chrome/pwa/boot.jsm#L196-L202) in the `final-ui-startup` event. These sources are registered for all locales that are currently available (plus `en-US` in any case), as otherwise Firefox would think all standard language packs are already installed and wouldn't download them. This may need some improvements in the future, but doesn't seem to be the cause of the main problem.

Then, on each page where they are needed, specific Fluent files are loaded with [`document.l10n.addResourceIds`](https://github.com/filips123/PWAsForFirefox/blob/a9b668b9a280398f241f4ecbcb69a1af55647ec8/native/userchrome/profile/chrome/pwa/content/preferences.jsm#L15). This should work the same as loading them with `link rel="localization"`, except it's easier to do it from JS.

The problem is that when my own resources and normal Firefox resources are loaded at the same time, the localization system breaks and returns only English messages, regardless of what the chosen locale is. Interestingly, when only my resources (or only Firefox resources) are loaded, they seem to work fine.

I tried a bunch of things (changed how filesources are registered, registered each language in a separate filesource, created a new `DOMLocalization` instance, etc.), but I couldn't fix the problem. However, I think I found where this problem might happen, I just don't know why it happens and how to fix it.

---

First, I did some preparation for testing:

1. Download language pack for some language (for example, Slovene).
2. Create a test `localization/sl/widgets.ftl` file (for example, for Slovene) and put some messages in it. The keys should be the same as in the English version, messages can be anything (as this is just a test), but they should be different from the English version.

Then, I tested a few things in the browser toolbox console:

```js
async function getBundles (locales, resources) {
  const registry = L10nRegistry.getInstance()
  const generator = registry.generateBundles(locales, resources)
  const bundles = []
  while (true) {
    const result = await generator.next()
    if (result.done) break
    bundles.push(result.value)
  }
  return bundles
}
```

This is just a simple function that returns all bundles for the specified locales and resource IDs. Normally, this should probably return two bundles, one for each language.

I tested that this is the case when only one resource ID is provided:

```js
await getBundles(["sl", "en-US"], ["browser/aboutDialog.ftl"])
// Array [ FluentBundle, FluentBundle ]
// 0: FluentBundle { locales: (1) [ "sl" ] }
// 1: FluentBundle { locales: (1) [ "en-US" ] }
```

Two bundles are generated, one for each locale. It works the same when I use my own resource ID, and I can even test getting specific messages:

```js
bundles = await getBundles(["sl", "en-US"], ["pwa/widgets.ftl"]) 
// Array [ FluentBundle, FluentBundle ]
// 0: FluentBundle { locales: (1) [ "sl" ] }
// 1: FluentBundle { locales: (1) [ "en-US" ] }

bundles[0].formatPattern(bundles[0].getMessage('toolbar-button-mute').attributes.label)
// "Preklopi zvok" 

bundles[1].formatPattern(bundles[1].getMessage('toolbar-button-mute').attributes.label)
// "Toggle Sound" 
```

However, when getting bundles for both resource ID, only the English bundle is returned:

```js
await getBundles(["sl", "en-US"], ["pwa/widgets.ftl", "browser/aboutDialog.ftl"])
// Array [ FluentBundle ]
// 0: FluentBundle { locales: (1) [ "en-US" ] }
```

I don't know why this happens and how it fix it. However, I think the bundles are generated with [this Firefox function](https://searchfox.org/mozilla-central/rev/5ad3692e95f0d1bd31134783bb916b70c489335a/intl/l10n/rust/l10nregistry-rs/src/registry/asynchronous.rs#187).

Do you maybe know why this happens and how to fix it?

I will probably try to debug this at some point or maybe ask someone who works on Firefox localization (and in this case, I will probably need to prepare a better reproducible example) at some point, but I don't know when I'll have time.

**Comment by surapunoyousei** [comment] 2024-01-22 13:51
Frankly, I have never used this method and I have no control over it.

I have asked other developers and asked the community but no information.

PS: Did you try to use `new Localization()` ?
```JS
function getl10n() {
    const l10n = new Localization(
      ["browser/floorp.ftl", "branding/brand.ftl"],
      true
    );
    return l10n;
  },

let l10n = getl10n();
let result = l10n.formatValueSync("workspace-default-name");
console.log(result);
  ```

**Comment by filips123** [comment] 2024-01-22 20:58
That also didn't work. As soon as I try to include one file from Firefox and one from PWAsForFirefox, all messages get returned in English.

I will try to create a minimal reproducible example and then maybe ask on [Mozilla Discourse](https://discourse.mozilla.org), [Mozilla Chat](https://chat.mozilla.org/) or Bugzilla.

**Comment by surapunoyousei** [comment] 2024-01-22 23:43
It's recommended.

**Comment by filips123** [comment] 2024-01-23 18:39
I created a topic on [Mozilla Discourse](https://discourse.mozilla.org/t/problems-with-fluent-when-loading-resources-with-autoconfig-startup-scripting-userchrome-js/126723) and repared a [minimal example](https://github.com/filips123/Firefox-AutoConfig-Localization). If I don't receive any suggestions in a few days, I'll probably also ask on Mozilla Chat.

**Comment by filips123** [comment] 2024-02-20 19:45
I found a fix for this issue. The problem was that Firefox wants to have all localization sources in one metasource per language, but I was registering all custom sources into the same metasource. I fixed that [here](https://github.com/filips123/PWAsForFirefox/commit/ed95d39388e89f143d9031900ae66366a1ce946c).

Now, localization is almost ready, and messages can already be translated on Crowdin.

However, there is still one problem... When "skip untranslated strings" is enabled on Crowdin, Crowdin will ignore messages with only attributes, even though they are translated. Because most messages here contain only attributes, this means that most messages won't get exported, even though they are translated. I've contacted Crowdin support about this, so hopefully it can get fixed. In case that won't be fixed soon, I will probably disable that option, but that means that a lot of actually untranslated messages will be exported, which will probably increase file size quite a bit.

**Comment by surapunoyousei** [comment] 2024-02-21 09:36
I agree with you on this as I also use Crowdin.

I have given up on this.

**Comment by filips123** [comment] 2024-03-29 17:14
Crowdin has fixed the issue so now Fluent files export properly even with "skip untranslated strings" enabled. So, I will now close this issue as localization has been implemented everywhere.

Messages can be translated [on Crowdin](https://crowdin.com/project/firefoxpwa) and will get merged in the next release.

**Closed by filips123** 2024-03-29 17:14 UTC
Labels: enhancement
