### ISSUE TITLE
Extension cannot detect the native connector on Ubuntu 23.04

### ISSUE THREAD

**Issue by TylerMS887** [filips123/PWAsForFirefox#325] opened 2023-04-22 19:39 UTC
@filips123 (Sorry for the ping, the bug should be classified as unbreak now if we were using Phabricator.)

### Description

Unknown. No logs available.
Strange, since the command line program is working.

### Steps to Reproduce

Install PWAsForFirefox and the native connector, on Ubuntu 23.04.

### Affected Websites

None, relates to native connector itself.

### Environment

* Operating system: Ubuntu 23.04
* System architecture: x86_64
* Desktop environment: GNOME
* Installation method: DEB
* PWAsForFirefox extension version: 2.5.0
* PWAsForFirefox native version: 2.5.0
* Firefox version: 112.0.1, Mozilla Firefox for Ubuntu, canonical - 1.0

**Comment by filips123** [comment] 2023-04-30 17:50
Did you see any such popup when first installing PWAsForFirefox and going to the setup page? You would need to accept it to be able to use PWAsForFirefox, as you seem to be using Firefox Snap.

![popup](https://user-images.githubusercontent.com/16626308/235367014-2c8cf1b1-e5b3-4866-9b55-17609031af6b.png)

If you didn't see it for some reason or accidentally denied it, you will have to allow it again. Apparently, you can do this "from the privacy settings" but I couldn't find where... Another option is to grant that permission via the command line:

```sh
flatpak permission-set webextensions firefoxpwa snap.firefox yes
```

After you grant the permission, you may need to restart Firefox. Or maybe even better, grant it while Firefox is closed.

You need to install Flatpak for this even though you use Snap, as it's used as an interface to manage `xdg-desktop-portal` permissions. You can later uninstall it if you do not use it.

**Comment by mackuz** [comment] 2023-04-30 19:34
Did not find that setting in Software center but your recommendation worked for me.

**Comment by badlogin** [comment] 2023-05-09 15:22
Same issue on 23.04, but Firefox is installed from PPA and I have not seen any permission pop-ups or settings

**Comment by badlogin** [comment] 2023-05-10 14:44
that tar.gz2 version completes the installation successfully, the version from PPA shows "Mozilla Firefox for Ubuntu, canonical - 1.0", the version from the website is just "113.0 (64-bit)"

**Comment by filips123** [comment] 2023-05-13 15:59
It seems this might be a bug in Firefox from PPA. I don't know how to fix it.

**Comment by olalderh** [comment] 2023-05-23 21:47
> Did you see any such popup when first installing PWAsForFirefox and going to the setup page? You would need to accept it to be able to use PWAsForFirefox, as you seem to be using Firefox Snap.
> 
> ![popup](https://user-images.githubusercontent.com/16626308/235367014-2c8cf1b1-e5b3-4866-9b55-17609031af6b.png)
> 
> If you didn't see it for some reason or accidentally denied it, you will have to allow it again. Apparently, you can do this "from the privacy settings" but I couldn't find where... Another option is to grant that permission via the command line:
> 
> ```shell
> flatpak permission-set webextensions firefoxpwa snap.firefox yes
> ```
> 
> After you grant the permission, you may need to restart Firefox. Or maybe even better, grant it while Firefox is closed.
> 
> You need to install Flatpak for this even though you use Snap, as it's used as an interface to manage `xdg-desktop-portal` permissions. You can later uninstall it if you do not use it.
> 
> _Edit:_ And if you can find where those privacy settings to manage desktop portal permissions are, please let me know...

Thanks! I fixed it via command line. I found that this prompt for permission does appear in firefox dev, and also with any firefox running on Ubuntu from a USB memory. The only problem appears to be with stable/nightly version of firefox with Ubuntu already installed on a local drive.

**Comment by filips123** [comment] 2023-05-26 09:57
I'll close this issue because there isn't much I can do. As Firefox from the Mozilla website detects the native connector properly, I think manifests are set up correctly. So, the problem is with specific versions of Firefox that I cannot fix.

Here are steps how you can fix this issue depending on your setup:

* **If Firefox Snap does not work:** Allow it to access native messaging [with a command](https://github.com/filips123/PWAsForFirefox/issues/325#issuecomment-1529095166). Although the permission popup should automatically show, it appears this is not always the case. Maybe this should be reported to Ubuntu/Snap. Related issues: #76, #264

* **If Firefox Flatpak does not work:** Flatpak does not support native messaging yet, but they are working on supporting it. Related issues: #76, #142

* **If Firefox from PPA/distro repository does not work:** It appears that Firefox distributed with some distributions can have bugs that break native messaging. This should also be reported to the maintainers of that repository. Related issues: #283, #313

If you have other similar problems, it's a good test to check if other addons that use native messaging (KeePassXC, Plasma Integration, etc.) work with your setup. If they also do not work, it's probably a problem with the Firefox version. If they do work, it might be a problem with PWAsForFirefox.

**Closed by filips123** 2023-05-26 09:57 UTC
Labels: bug

**Comment by davidjao** [comment] 2024-07-21 20:19
I was able to mostly fix this problem on Ubuntu by adding a few lines to `/etc/apparmor.d/usr.bin.firefox`:
```
/usr/libexec/firefoxpwa-connector ixr,
/usr/bin/firefoxpwa ixr,
owner @{HOME}/.local/share/** rw,
```
I say "mostly" because, although this change was enough to get the PWA that I was interested in (Microsoft Teams) to install, actually running the app still required some command line magic, which I can explain if anyone is interested, but doesn't seem to be related to this particular bug.
