### ISSUE TITLE
On App launch: %1 is not a valid Win32 application (os. error 193)

### ISSUE THREAD

**Issue by CelularBat** [filips123/PWAsForFirefox#522] opened 2024-07-14 09:19 UTC
### Description

When I try to launch installed web app it says:
> %1 is not a valid Win32 application (os. error 193)

### Steps to Reproduce

1. Install any site as application
2. Click "launch web app"
3. See the error

### Environment

* Operating system: Windows 8.1
* Extension version: 2.12.1
*  Native version: 2.12.1
*  Runtime version: 128.0
*  Firefox version: LibreWolf 116.0.3-1

**Comment by filips123** [comment] 2024-07-17 07:25
This is probably because Firefox does not support Windows 8.1 anymore. As a temporary solution, you can manually download and extract Firefox ESR 115 (or just copy your existing LibreWolf installation) into the runtime directory, replacing any existing files there. The runtime directory is `%APPDATA%\FirefoxPWA\runtime\`.

However, Windows 8.1 is not officially supported by Microsoft, Firefox and PWAsForFirefox anymore. Firefox ESR 115 will be EOL by September, and PWAsForFirefox will probably stop supporting Windows 8.1 very soon, so you should upgrade to a supported system soon (Windows 10/11, Linux or macOS).

**Comment by filips123** [comment] 2024-08-04 13:10
I'll close this issue as it's likely caused by Windows 8.1.

**Closed by filips123** 2024-08-04 13:10 UTC
Labels: bug

**Comment by CelularBat** [comment] 2024-08-05 22:23
> This is probably because Firefox does not support Windows 8.1 anymore. As a temporary solution, you can manually download and extract Firefox ESR 115 (or just copy your existing LibreWolf installation) into the runtime directory, replacing any existing files there. The runtime directory is `%APPDATA%\FirefoxPWA\runtime\`.
> 
> However, Windows 8.1 is not officially supported by Microsoft, Firefox and PWAsForFirefox anymore. Firefox ESR 115 will be EOL by September, and PWAsForFirefox will probably stop supporting Windows 8.1 very soon, so you should upgrade to a supported system soon (Windows 10/11, Linux or macOS).

Yes, thx, replacing runtime application with an older Firefox just fixed the problem.
