### ISSUE TITLE
Option to choose your own icon for your web apps, instead of just relying on the site's favicon.

### ISSUE THREAD

**Issue by linusrg1** [filips123/PWAsForFirefox#228] opened 2022-09-28 20:36 UTC
### Problem Description

You are seemingly unable to select an image file to use as the web app's icon, and have to rely on the site's favicon instead. This can be an issue, as some sites don't really have a proper favicon at times, and most of the favicons that exist for various sites, end up looking blurry when enlarged to the size required for use as an app icon.

### Proposed Solution

To allow the user to choose an image to use as the icon for their web app. This way, a nice, high res version of the site's logo can be used over the blurry favicon that the site provides, and that this extension uses as the web app's icon. It is also a nice to have if a certain site you want to use as a web app either doesn't have a favicon, or the one that is provided/most likely to be pulled by a program like PWAsForFirefox, is a generic favicon offered by the service that hosts the site, and one that that service uses for a lot of its services. Like Google web apps for example. A lot of the time when I use a program that saves links for your convenience, like Tabless for example, a lot of Google web apps end up using the generic Google logo as their favicon. For some reason this favicon is always the one to be pulled in for Google web apps. Instead of the correct favicon, like the specific one for Google Docs, Google Drive, or Google Classroom for example.  This wouldn't be an issue, if there was a way to manually change the icon used for the web app to a more distinct one, so you could tell that app apart easier. 

### Additional Information

I know you can manually change the icon for the .desktop/shortcut that this application creates, but it would be nice if this extension allowed you to do it while configuring the web app.

**Comment by filips123** [comment] 2022-10-03 20:41
I would like to implement this eventually, but there are some problems that make this harder. For example, adding a file input to an extension popup doesn't work, because Firefox will close it immediately after the file selection dialog opens.

Anyways, this issue is duplicate of #128 so I'll close it.

**Closed** 2022-10-03 20:41 UTC
Labels: enhancement
