### ISSUE TITLE
Adding Polarr crashes the entire browser

### ISSUE THREAD

**Issue by kreaninw** [filips123/PWAsForFirefox#152] opened 2022-05-12 22:10 UTC
### Description

Adding **[Polarr](https://photoeditor.polarr.co)** crashes the entire browser. The crash report is shown below:

```
AdapterDeviceID: 0x5917
AdapterDriverVendor: mesa/iris
AdapterDriverVersion: 22.0.3.0
AdapterVendorID: 0x8086
Add-ons: %7B9a41dee2-b924-4161-a971-7fb35c053a4a%7D:2.1.0,firefoxpwa%40filips.si:1.4.0,langpack-th%40firefox.mozilla.org:100.0buildid20220428.192727,%40firefox:5.1.0,webcompat%40mozilla.org:100.2.1buildid20220504.194401,doh-rollout%40mozilla.org:2.0.0,formautofill%40mozilla.org:1.0.1,pictureinpicture%40mozilla.org:1.0.0,screenshots%40mozilla.org:39.0.1,default-theme%40mozilla.org:1.3,addons-search-detection%40mozilla.com:2.0.0,google%40search.mozilla.org:1.2,amazondotcom%40search.mozilla.org:1.3,wikipedia%40search.mozilla.org:1.1,bing%40search.mozilla.org:1.3,ddg%40search.mozilla.org:1.1
AvailablePageFile: 0
AvailablePhysicalMemory: 161067008
AvailableSwapMemory: 8142450688
AvailableVirtualMemory: 2866810880
BackgroundTaskMode: 0
BuildID: 20220509144909
ContentSandboxCapabilities: 119
ContentSandboxCapable: 1
ContentSandboxLevel: 4
CrashTime: 1652392679
DOMFissionEnabled: 1
DOMIPCEnabled: 1
DesktopEnvironment: gnome
ExperimentalFeatures: devtools.inspector.compatibility.enabled
HeadlessMode: 0
InstallTime: 1652380008
IsWayland: 1
LinuxUnderMemoryPressure: 0
MozCrashReason: Redirecting call to abort() to mozalloc_abort

Notes: FP(D00-L1000-W00000000-T000) WR! WR+ EGL? EGL- GL Context? GL Context+ WebGL? WebGL+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 350
StartupCrash: 0
StartupTime: 1652392334
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20220509144909","version":"100.0","vendor":"Mozilla","displayVersion":"100.0","platformVersion":"100.0","xpcomAbi":"x86_64-gcc3","updaterAvailable":false},"partner":{"distributionId":"fedora","distributionVersion":"1.0","partnerId":null,"distributor":"fedora","distributorChannel":"fedora","partnerNames":["fedora"]},"system":{"memoryMB":7828,"virtualMaxMB":null,"cpu":{"count":8,"cores":4,"vendor":"GenuineIntel","family":6,"model":142,"stepping":10,"l2cacheKB":256,"l3cacheKB":6144,"speedMHz":3400,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Linux","version":"5.17.6-300.fc36.x86_64","locale":"en-US"},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":null,"adapters":[{"description":"Mesa Intel(R) UHD Graphics 620 (KBL GT2)","vendorID":"0x8086","deviceID":"0x5917","subsysID":null,"RAM":0,"driver":null,"driverVendor":"mesa/iris","driverVersion":"22.0.3.0","driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":1280,"screenHeight":720}],"features":{"compositor":"webrender","hwCompositing":{"status":"available"},"gpuProcess":{"status":"unused"},"wrQualified":{"status":"available"},"webrender":{"status":"force_enabled"},"wrCompositor":{"status":"blocklisted:FEATURE_FAILURE_WEBRENDER_COMPOSITOR_DISABLED"},"wrSoftware":{"status":"available"},"openglCompositing":{"status":"available"},"omtp":{"status":"unused"}}},"appleModelId":null,"hasWinPackageId":null},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":true,"telemetryEnabled":false,"locale":"en-US","intl":{"requestedLocales":["en-US","th"],"availableLocales":["en-US","th"],"appLocales":["en-US","th"],"systemLocales":["en-US"],"regionalPrefsLocales":["en-US"],"acceptLanguages":["en-US","en"]},"update":{"channel":"release","enabled":true,"autoDownload":false,"background":false},"userPrefs":{"browser.search.region":"CL","browser.search.widget.inNavBar":false,"browser.urlbar.quicksuggest.dataCollection.enabled":false,"browser.urlbar.suggest.quicksuggest.nonsponsored":false,"browser.urlbar.suggest.quicksuggest.sponsored":false,"browser.urlbar.suggest.bestmatch":true,"gfx.webrender.all":true,"network.trr.strict_native_fallback":false,"widget.content.allow-gtk-dark-theme":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":4,"contentWin32kLockdownState":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":false,"defaultSearchEngine":"google-b-d","defaultSearchEngineData":{"loadPath":"[other]addEngineWithDetails:google@search.mozilla.org","name":"Google","origin":"default","submissionURL":"https://www.google.com/search?client=firefox-b-d&q="}},"profile":{"creationDate":19123,"firstUseDate":19123},"addons":{"activeAddons":{"webcompat@mozilla.org":{"version":"100.2.1buildid20220504.194401","scope":1,"type":"extension","updateDay":19123,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compatibility Interventions","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19123,"signedState":3},"{9a41dee2-b924-4161-a971-7fb35c053a4a}":{"version":"2.1.0","scope":1,"type":"extension","updateDay":19123,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Choose what video codec YouTube should play for you","name":"enhanced-h264ify","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19123,"signedState":2},"doh-rollout@mozilla.org":{"version":"2.0.0","scope":1,"type":"extension","updateDay":19121,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"This used to be a Mozilla add-on that supported the roll-out of DoH, but now only exists as a stub t","name":"DoH Roll-Out","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19115},"formautofill@mozilla.org":{"version":"1.0.1","scope":1,"type":"extension","updateDay":19121,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19115},"pictureinpicture@mozilla.org":{"version":"1.0.0","scope":1,"type":"extension","updateDay":19121,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Fixes for web compatibility with Picture-in-Picture","name":"Picture-In-Picture","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19115},"screenshots@mozilla.org":{"version":"39.0.1","scope":1,"type":"extension","updateDay":19121,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Take clips and screenshots from the Web and save them temporarily or permanently.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19115},"firefoxpwa@filips.si":{"version":"1.4.0","scope":1,"type":"extension","updateDay":19124,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"A tool to install, manage and use Progressive Web Apps (PWAs) in Mozilla Firefox","name":"Progressive Web Apps for Firefox","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19124,"signedState":2},"langpack-th@firefox.mozilla.org":{"version":"100.0buildid20220428.192727","scope":1,"type":"locale","updateDay":19124,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Language pack for Firefox for th","name":"ไทย Language Pack","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19124,"signedState":2},"@firefox":{"version":"5.1.0","scope":1,"type":"extension","updateDay":19124,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Professionally edit any photo on the internet with one click. Works offline.","name":"Polarr Photo Editor","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19124,"signedState":2}},"theme":{"id":"default-theme@mozilla.org","blocklisted":false,"description":"Follow the operating system setting for buttons, menus, and windows.","name":"System theme — auto","userDisabled":false,"appDisabled":false,"version":"1.3","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":19123,"updateDay":19123},"activeGMPlugins":{"dummy-gmp":{"version":"0.1","userDisabled":false,"applyBackgroundUpdates":1}}},"experiments":{"bug-1767475-rollout-enable-pip-subtitles-pref-in-release-release-100-101":{"branch":"active","type":"normandy-prefrollout","enrollmentId":"9a94543f-cc3d-452b-ba77-bae907922957"}}}
Throttleable: 1
TotalPageFile: 16415010816
TotalPhysicalMemory: 8207810560
URL: moz-extension://70db21d7-351a-48a2-90a2-3965a3ff6ad2/sites/install.html
UptimeTS: 345.42619009
Vendor: Mozilla
Version: 100.0
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.
```

### Steps to Reproduce

1. Go to [Polarr](https://photoeditor.polarr.co)
2. Adding it as a PWA in PWAsForFirefox
3. Firefox crashes.

### Additional Information

-

### Affected Websites

[https://photoeditor.polarr.co](https://photoeditor.polarr.co)

### Environment

* Operating system: Fedora 36
* System architecture: 64-bit
* Desktop environment: GNOME
* Installation method: RPM
* PWAsForFirefox extension version: 1.4.0
* PWAsForFirefox native version: I don't know. But I followed the instruction and installed it today.
* Firefox version: 100

**Comment by filips123** [comment] 2022-05-13 19:57
This is interesting, but I cannot reproduce it. I'm not sure why extension would crash the entire browser, so it might be some problem with Firefox or something else. Can you also share your crash ID from `about:crashes` as seeing complete crash report might be helpful?

**Comment by filips123** [comment] 2022-06-22 12:11
Closing because of the reasons mentioned above. If it still happens, please share your crash IDs and I will reopen the issue.

**Closed by filips123** 2022-06-22 12:11 UTC
Labels: bug
