### ISSUE TITLE
FR: Installation without admin rights

### ISSUE THREAD

**Issue by thehotery** [filips123/PWAsForFirefox#178] opened 2022-07-07 04:49 UTC
Installation without admin rights on windows. Is it possible?  It espacially looks strange when browser itself dont require it (and many other software today)

**Comment by filips123** [comment] 2022-07-07 11:20
It is possible, but not very easy as you will have to change source code a bit and compile it. See #111 for details.

I will try to implement better support for per-user installs (#129) in the future.

**Comment by filips123** [comment] 2022-07-22 17:28
I will close this as it's duplicate of #129.

**Closed by filips123** 2022-07-22 17:28 UTC
Labels: enhancement
