### ISSUE TITLE
Firefox extension setup never finished in Ubuntu 23.04

### ISSUE THREAD

**Issue by mackuz** [filips123/PWAsForFirefox#331] opened 2023-04-30 13:36 UTC
### Description

Firefox is installed with snap (I've also tried apt version with no luck). Firefoxpwa is installed from ppa. Setup is started and gives me to accept license and shows howto to install firefoxpwa, but shows me an error: "Error: An unexpected error occurred". That's all it shows. Firefox restart does not help.

That's all I have.

### Steps to Reproduce

1. Install Progressive Web Apps for Firefox extension
2. Accept license agreement
3. Install firefoxpwa package

### Additional Information

This is the message from firefoxpwa:
"You have successfully installed the native part of the PWAsForFirefox project
You should also install the Firefox extension if you haven't already
Download: https://addons.mozilla.org/firefox/addon/pwas-for-firefox/"

### Affected Websites

* ...
* ...

### Environment

* Operating system: Ubuntu 23.04
* System architecture: amd64
* Desktop environment: Gnome on Wayland
* Installation method: snap and deb for Firefox, official firefoxpwa deb from ppa
* PWAsForFirefox extension version: 2.5.0
* PWAsForFirefox native version: 2.5.0
* Firefox version: 112.0.2 (64-bit)

**Comment by mackuz** [comment] 2023-04-30 13:59
Was able to install web app via command line though. In it's own new profile. But browser extension does not show this app nor it's profile.

**Comment by filips123** [comment] 2023-04-30 17:22
This seems like a duplicate of #325. I'm still checking how to fix it though.

**Closed by filips123** 2023-04-30 17:22 UTC
Labels: bug
