### ISSUE TITLE
Not able to play videos on Twitch.tv

### ISSUE THREAD

**Issue by f73** [filips123/PWAsForFirefox#310] opened 2023-03-10 16:41 UTC
### Description

Since today's firefox update to version 110.0.1-3 from 110.0.1-2 on Arch Linux, Twitch is not able to play videos, throwing
`Your browser encountered an error while decoding the video. (Error #3000)`. Spotify error is: `Something went wrong with playback`. Everything was working as expected yesterday...

### Steps to Reproduce

1. Go to https://www.twitch.tv
2. Select any stream and press play button

### Additional Information
Twitch:
![Screenshot from 2023-03-10 17-33-27](https://user-images.githubusercontent.com/16547841/224371299-f8233930-e322-4e74-8528-bc490a5c7658.png)
Spotify:
![Screenshot from 2023-03-10 17-35-09](https://user-images.githubusercontent.com/16547841/224371597-6c85f937-f82f-43ee-99bf-bf5b7365b72f.png)

### Affected Websites

* https://www.twitch.tv
* https://open.spotify.com/

### Environment

* Operating system: Arch Linux
* System architecture: x64
* Desktop environment: GNOME Shell 43.3
* Installation method: 
* PWAsForFirefox extension version: 2.4.1
* PWAsForFirefox native version:
* Firefox version: 110.0.1-3

Thank you!

**Comment by filips123** [comment] 2023-03-13 18:20
It works fine for me on Windows. I haven't tested it on Arch yet, but I don't see how PWAsForFirefox could affect video playback. Please check if it works with Firefox that you download [from the official website](https://www.mozilla.org/firefox/all). Also, try to disable any extensions and privacy protections and make sure DRM is enabled.

**Comment by f73** [comment] 2023-03-14 11:27
> Please check if it works with Firefox that you download [from the official website](https://www.mozilla.org/firefox/all). Also, try to disable any extensions and privacy protections and make sure DRM is enabled.

I have done that, forgot  to mention in additional info when I opened issue.

**Comment by f73** [comment] 2023-03-14 11:46
I just found out that firefox 110.0.1 (linux 64-bit) downloaded from mozilla, [official website](https://www.mozilla.org/firefox/all), will not play streams on twitch, at least not for me, youtube works just fine.

I have managed to fix issues described in original post by copying content of `/usr/lib/firefox` to `~/.local/share/firefoxpwa/runtime`

**Comment by filips123** [comment] 2023-03-14 19:43
Then, it's probably a bug with Firefox, maybe something related to DRM or codecs. You can try to report it to Bugzilla.

I'll close this issue as it does not seem to be caused by PWAsForFirefox.

**Closed by filips123** 2023-03-14 19:43 UTC
Labels: bug, question, could not reproduce
