### ISSUE TITLE
Random Firefox window opens from time to time when I first log in.

### ISSUE THREAD

**Issue by linusrg1** [filips123/PWAsForFirefox#227] opened 2022-09-28 20:12 UTC
### Description

Sometimes when I log in, a boarderless Firefox window automatically opens to the Firefox homepage, for some reason. This did not happen with Firefox before I installed this extension. 

### How to encounter this bug:
Just log in to your computer, and every now and then a boarderless Firefox window will open with no user intervention. 
### Additional Information
Screenshot will be provided next time it happens. As for logs, I don't know what I could provide in therms of this. But if you tell me what would be helpful, I will gladly paste the requested information here. 

### Environment

* Operating system: openSUSE Tumbleweed (20220926)
* System architecture: x64
* Desktop environment: KDE 5.25.5
* Installation method: openSUSE rpm
* PWAsForFirefox extension version: 2.1.0
* PWAsForFirefox native version: 2.1.0
* Firefox version: 104.0.2

**Comment by filips123** [comment] 2022-09-28 20:30
To get logs of the native program, create an empty `DEBUG` file (with no file extension) in the `~/.local/share/firefoxpwa` directory.  After this problem happens, check `firefoxpwa.log`, `firefoxpwa-stdout.log` and `firefoxpwa-stderr.log` in the same directory.

Also, to get Firefox runtime logs:
1. Inside that window that opened:
2. Open developer tools (press F12) and their settings (then press F1).
3. Enable "browser chrome and add-on debugging toolboxes" and "remote debugging", then close developer tools.
4. Press Ctrl+Alt+Shift+I, accept the prompt.
5. Go to console tab in the opened window and copy any errors/messages.

I don't know why this happens, but just a thought: Do you have your OS configured to automatically re-open apps that were running when it was shut down? If so, maybe it tried to open that PWA but failed.

**Comment by linusrg1** [comment] 2022-10-01 17:21
Sorry for not responding it is not happening now. And I am stil tryna get it to happen again. So I don't know what is causing the issue.

**Comment by filips123** [comment] 2022-10-31 18:47
Maybe this issue was caused by the session restore problem (#175, #226), which has been fixed in 2.1.1. So, I'll close this issue for now, and if it still happens to you on the latest version please comment and I'll reopen it.

**Closed by filips123** 2022-10-31 18:47 UTC
Labels: bug
