### ISSUE TITLE
Save Window position and size

### ISSUE THREAD

**Issue by fernandeusto** [filips123/PWAsForFirefox#515] opened 2024-06-15 00:01 UTC
It would be nice to be able to save the size and position of the window for each application

**Comment by filips123** [comment] 2024-06-16 08:34
This seems to be a duplicate of #256. It's quite complex to implement, so it will probably take quite a lot of time. As a workaround, window position and size should persist if you install each web app into a separate profile.

**Closed by filips123** 2024-06-16 08:34 UTC
Labels: enhancement
