### ISSUE TITLE
Opening an app doesn't work as expected

### ISSUE THREAD

**Issue by lasersPew** [filips123/PWAsForFirefox#162] opened 2022-06-03 13:22 UTC
### Description
1. When you click the PWA shortcut from the extension or start, it opens a new window. there are no signs of the actual PWA opening.
2. When you click the PWA shortcut in the address bar(check bug-1-*.png), it opens a new window and has the PWA opened but just like in # 1, the tabs aren't hidden and it looks like its a new window. Earlier, instead of opening a new window, it opens a new tab with the PWA opened.

### Steps to Reproduce

i. The normal way:
1. Click the Windows icon(or the Firefox PWA extension)
3. Find the name of the PWA
4. Click the app to open.
5. See error(it opens a new blank window)

i. The URL intent way:
1. Go to the site in which you have the PWA installed.
2. Click the 'go somewhere' button in address tab.
3. Find the name of the PWA.
4. Click the app to open.
5. See error(it opens a new blank window)

### Additional Information
A few things to disclose:
- has vscode installed along with web extensions for vscode from firefox
- has virtualbox with linux installed in it.

![bug-1-2](https://user-images.githubusercontent.com/87552756/171862580-ea589061-59be-4cf1-9017-72232a0c6552.png)
![bug-1-3](https://user-images.githubusercontent.com/87552756/171862584-d0bb70b3-05cd-4481-816e-a3735c564f1b.png)
![bug-2](https://user-images.githubusercontent.com/87552756/171862591-61fdf535-a338-4600-9a77-9be0f84ce211.png)
![bug-1](https://user-images.githubusercontent.com/87552756/171862594-22a2a5a1-995c-478d-9b07-81311af6a88b.png)
![bug-1-1](https://user-images.githubusercontent.com/87552756/171862597-80041d43-334f-49db-84ec-673b3cc501f2.png)

### Affected Websites

https://mangadex.org
https://notion.so
https://facebook.com
https://messenger.com
https://todoist.com
https://youtube.com
(basically, all the websites i installed.)

### Environment

* Operating system: Windows 11 22H1 22000.708
* System architecture: amd64
* Installation method: winget(i also tried the exe files)
* PWAsForFirefox extension version: 1.4.0
* PWAsForFirefox native version: 1.4.0
* Firefox version: 101.0
* Device: Lenovo Ideapad 3

**Comment by lasersPew** [comment] 2022-06-03 13:24
Edit: when there's a open window with the pwa(i mean the window activity was triggered by the pwa) and you clicked to open another pwa, it opens in another tab of the same window.

**Comment by filips123** [comment] 2022-06-03 13:36
This has been fixed in [v1.4.2](https://github.com/filips123/PWAsForFirefox/releases/tag/v1.4.2), however, Mozilla still hasn't reviewed and approved the new extension version. This means you will have to manually download it from [here](https://github.com/filips123/PWAsForFirefox/releases/tag/v1.4.2) (or use `winget` to update it). The extension will then say it's outdated but this is fine until Mozilla approves a new version.

Closing as duplicate of #154, #155.

**Closed by filips123** 2022-06-03 13:36 UTC
Labels: bug

**Comment by lasersPew** [comment] 2022-06-03 13:46
Do you have the xpi file for the extension?

**Comment by filips123** [comment] 2022-06-03 13:59
No, because it needs to be approved by Mozilla in order to install it. However, it doesn't matter, because the extension hasn't changed. You only need to update the program.
