### ISSUE TITLE
Can not install extension to switch user agent

### ISSUE THREAD

**Issue by itsoulos** [filips123/PWAsForFirefox#437] opened 2024-01-01 12:48 UTC
Dear all,
I want to install a user agent switcher addon in pwa in order to make skype work in Asahi Linux but I have the following error
![Screenshot_20240101_144758](https://github.com/filips123/PWAsForFirefox/assets/6303921/61029625-3acc-4661-92a0-5d5f0db51973)

**Comment by filips123** [comment] 2024-01-01 17:29
It works fine for me on Windows and Ubuntu.

Please obtain the runtime logs using the instructions from [here](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-runtime-logs). You may also need to select "Multiprocess" at the top of the browser toolbox window.

Also, I have a few more questions:

* When does the error appear? Immediately when you load the page, after clicking "Add to Firefox" or after confirming the installation in a popup?
* Does this popup show?
  ![slika](https://github.com/filips123/PWAsForFirefox/assets/16626308/f5077e07-15fe-475b-b6aa-4b2adada71c3)
* Does it with other extensions?
* Does it work in a new PWA profile?

**Comment by itsoulos** [comment] 2024-01-01 17:41
Thank you for your response,

1) The problem appears when I try to load any plugin from the firefox running the web app
2) the popup that you send me never appears
3) I face the same problem with any other extension
4) I will try to create a new profile later today and I will report any message from the log file

**Comment by filips123** [comment] 2024-01-01 17:49
It's possible that something broke with the extension installation code. Another problem with the extension installation is #434, but I don't know if they are related, so I'll need logs for that.

**Comment by itsoulos** [comment] 2024-01-01 17:58
here is the log file
[console-export-2024-1-1_19-58-3.txt](https://github.com/filips123/PWAsForFirefox/files/13805486/console-export-2024-1-1_19-58-3.txt)

**Comment by filips123** [comment] 2024-01-01 18:07
This seems like a different issue than #434. It looks like the download failed for some reason. However, I still don't know why this happens...

Please also try to do this in a new PWA profile. If it works there, it's possible that some specific configuration broke the installation in the first profile. If the problem is also present in the new profile, it might be caused by some network issue.

**Comment by itsoulos** [comment] 2024-01-01 18:13
No the problem remains.
I did not have any network problem there
The runtime firefox is installed in a separate directory

~/.local/share/firefoxpwa/runtime

is this a problem?

**Comment by filips123** [comment] 2024-01-01 22:48
It is normal that the PWA runtime is separate from the default browser, and installed in `~/.local/share/firefoxpwa/runtime`. However, maybe you have some firewall or some other configuration that blocks this runtime from downloading addons?

**Comment by itsoulos** [comment] 2024-01-02 11:36
No, I have not any firewall.

**Comment by filips123** [comment] 2024-01-02 15:11
You can also check what happened to the request to download the addon. In the Browser Toolbox (`Ctrl+Alt+Shift+I`), go to the "network" tab. Try to install the addon and check if any request for `https://addons.mozilla.org/firefox/downloads/file/4098688/user_agent_string_switcher-0.5.0.xpi` (or similar) appears and if it succeded. If it didn't, you can probably check the status code and the response to see if there are any useful details why it failed.

You can also copy the request as HAR and attach it. However, in this case, before uploading it, check it and clean any sensitive information such as cookies. You can also use [Cloudflare's sanitizer](https://blog.cloudflare.com/introducing-har-sanitizer-secure-har-sharing/) to do this, although I'm not sure how reliable it is.

**Comment by itsoulos** [comment] 2024-01-02 16:06
No. It appears to block the xpi for some reason.
In order to make it work I use firefox esr (115) in the runtime directory
Could be that the reason of the problem?

**Comment by filips123** [comment] 2024-01-02 18:32
Well, I don't know.

If you download Firefox from [Mozilla website](www.mozilla.org/firefox/all/) and use it normally (without PWAs), does the addon installation work there?

**Comment by itsoulos** [comment] 2024-01-02 18:36
Well, that is the main problem for me. The machine that I use is a m1 mac with Asahi Linux and I could not find any relevant tar.gz in the mozilla web site

**Comment by filips123** [comment] 2024-01-02 18:42
So, the runtime that you use for PWAs is copied from the distro-provided Firefox, built for M1 ARM?

Then, one thing that you can try is to launch the runtime directly with something like:

```sh
~/.local/share/firefoxpwa/runtime/firefox --profile /tmp/some-empty-directory
```

And check if you can install addons. This should at least show if the problem is with some modifications that PWAsForFirefox is doing.

As a workaround, you can probably still install addons if you download the XPI file manually (maybe with curl) and then load the XPI directly into PWA runtime from `about:addons`.

**Comment by itsoulos** [comment] 2024-01-02 18:46
None of these two options worked.
The problem with the corrupted file remains

**Comment by filips123** [comment] 2024-01-02 18:54
This is really weird. Unfortunately, I don't know what causes this problem and how to solve it. Maybe it's a problem with Firefox version built for Asahi Linux. You should probably report it to the maintainers of Firefox package for Asahi or Mozilla.

**Comment by filips123** [comment] 2024-01-05 15:39
Considering this was probably the problem with Firefox, I'll close this issue.

**Closed by filips123** 2024-01-05 15:39 UTC
Labels: bug, could not reproduce
