### ISSUE TITLE
Links opened in a PWA don't open on main Firefox

### ISSUE THREAD

**Issue by matteoturini** [filips123/PWAsForFirefox#140] opened 2022-03-20 23:12 UTC
### Description

Any link clicked inside a PWA opens on it's own window instead of my main Firefox window.

### Steps to Reproduce

1. Go to any PWA app
2. Click on any link
3. Observe it open on the same app

### Additional Information

Not even `CTRL + Click` works

### Affected Websites

All of them

### Environment

* Operating system: Arch Linux
* System architecture: x86_64
* Desktop environment: Budgie
* Installation method: AUR (binary)
* PWAsForFirefox extension version: Don't know. Latest.
* PWAsForFirefox native version: Don't know. Latest.
* Firefox version: 98.0.1

**Comment by filips123** [comment] 2022-04-02 10:33
You can currently open links in main Firefox if you right-click on them and then select "Open Link in Default Browser". Alternatively, you could open a link in PWA Firefox and then use "Open in Browser" widget (available from the customization panel) to reopen it in a default Firefox.

However, if you just want to open non-PWA URLs in the main Firefox, I think it would be easier that you enable "Open out-of-scope URLs in a default browser". This way, any URL that does not belong to the PWA will automatically open in the main Firefox. However, if you're using PWA that uses SSO for login (such as most websites by Google, Microsoft and some others), you will also need to add their SSO page domains to "Domains always allowed to be opened in the PWA browser", otherwise, you won't be able to log in. For example, for Google you would need to set "accounts.google.com".

Adding keyboard shortcut to links is a bit harder, but I'll try to add an option for this.

**Comment by matteoturini** [comment] 2022-04-02 13:45
> I think it would be easier that you enable "Open out-of-scope URLs in a default browser".

I can't find this anywhere. Where is it?

**Comment by filips123** [comment] 2022-04-02 14:52
On the Firefox preferences/settings page, inside PWA Firefox.

<details>
<summary>Screenshots</summary>


![menu](https://user-images.githubusercontent.com/16626308/161388608-08670af5-930f-46c6-9177-57199f31e9c3.png)
![settings](https://user-images.githubusercontent.com/16626308/161388742-3d731e24-c160-4ea9-b171-0109b7cf8ca8.png)


</details>

**Comment by enricojonas** [comment] 2022-05-14 10:07
Hi, I am also interested in this and tried it out. Yes, the links now open in my default browser (Firefox), but at the same time the PWA closes. How can we keep the PWA open? Running this on Ubuntu 22.04 (Wayland) with the latest Firefox (No snap, deb version).

Thank you

**Comment by filips123** [comment] 2022-05-14 11:42
I think you could fix this if you select "Force links into a new window" in settings. With this enabled, all such links will first open in a new PWA window, but immediately close and open in the default browser while keeping original the PWA window open.

**Comment by enricojonas** [comment] 2022-05-16 06:02
Hi, that is the setting I already have. It's closing the PWA window and opening the link in the system default browser, so it's not working as intended most probably...

![image](https://user-images.githubusercontent.com/46678516/168528917-062bc5b7-7bec-4ed3-b9b1-e757ac5822d9.png)

**Comment by enricojonas** [comment] 2022-05-18 06:36
Hi, yes I tried restarting. I am trying with Outlook as PWA (https://outlook.office.com/mail/inbox). Unfortunately also the login doesn't stick so every time when I re-open the PWA I need to login again. And if I have the setting on it redirects med to login.microsoftonline.com (opening in my default browser since I guess this URL is not in scope).

**Closed** 2022-07-31 15:15 UTC
Labels: bug

**Comment by tfiers** [comment] 2022-12-05 23:21
I'm also testing with Outlook and it works for me: clicking a link opens it in main Firefox and the PWA is not closed.
Setting "Force links into a new window" was necessary to not close the PWA for me

**Comment by tfiers** [comment] 2022-12-06 00:08
I'm also testing with Outlook and it works for me: clicking a link opens it in main Firefox and the PWA is not closed.

I'm coming from Chrome with its PWA 'apps' (which opens link in main chrome automatically). It took me a bit to find this issue. This trick[^1] should maybe be documented somewhere new users see it? Not sure what would be a good place for it

[^1]: i.e. "Open out of scope URLs …" and "Force links into a new window"; with the "Domains always allowed" caveat.
Or, just a link to this issue and a mention of the contex menu option "Open Link in Default Browser" (which I didn't know existed).

**Comment by filips123** [comment] 2022-12-08 18:53
There is [a wiki page](https://github.com/filips123/PWAsForFirefox/wiki/App-Browser-Features) which lists most available options. But yeah, I agree that documentation should be better and easier to find. I've been thinking of creating a documentation website for a while, but I don't know when it will be done.
