### ISSUE TITLE
Unwritable user applications directory on macOS

### ISSUE THREAD

**Issue by yangchuansheng** [filips123/PWAsForFirefox#56] opened 2021-09-13 02:37 UTC
### Description

I've installed the extension on macOS and runtime, attempting to install any site using CLI:

```bash
$ firefoxpwa site install https://www.notion.so
```

result in an error:

```bash
02:31:00 [INFO] Installing the site
02:31:00 [INFO] Downloading the PWA manifest
02:31:01 [INFO] Parsing the PWA manifest
02:31:01 [ERROR] Failed to parse PWA manifest

Caused by:
    expected value at line 1 column 1
```

When I try installing site with extension, it result in another error:

![](https://cdn.jsdelivr.net/gh/yangchuansheng/imghosting1@main/img/202109131036860.png)

What am I doing wrong?

### Affected Websites

* www.notion.so
* any site

### Environment

* Operating system: macOS
* System architecture: x86_64
* Desktop environment: 
* Installation method:  homebrew
* FirefoxPWA extension version: 1.1.0
* FirefoxPWA native version: 1.1.0
* Firefox version: 92.0

**Comment by filips123** [comment] 2021-09-13 15:42
> I've installed the extension on macOS and runtime, attempting to install any site using CLI:

This is normal (or at least "not unexpected") because you need to provide a direct URL to the website manifest if you want to install it from CLI (for example, `firefoxpwa site install twitter.com/manifest.json`). However, https://www.notion.so does not have a PWA manifest so you will have to install it from extension.

> When I try installing site with extension, it result in another error:

And here is the real problem and I'm not completely sure why exactly it happens. Can you please check [troubleshooting steps](https://github.com/filips123/FirefoxPWA/wiki/Troubleshooting) and provide full log file? Maybe it provides more details why it failed.

@TitanNano Can you please try to debug and fix this?

It seems the error happens [here](https://github.com/filips123/FirefoxPWA/blob/192c47495e7f99becf84d9d36b2a38b349feba79/native/src/integrations/macos.rs#L282-L284). Perhaps it could be related to [change in Homebrew formula](https://github.com/Homebrew/homebrew-core/commit/22860e8902e3350523fe9a259bd5e99e73b3f9b8#diff-f4ab72b7b727d1b4ca1a7b750ca0668113b43d8f1eadf98bf2cc59df5ba9187f) where I changed all paths to use unversioned paths (to fix #55), but I'm not sure why it would cause permission denied error.

**Comment by yangchuansheng** [comment] 2021-09-13 16:28
> > I've installed the extension on macOS and runtime, attempting to install any site using CLI:
> 
> This is normal (or at least "not unexpected") because you need to provide a direct URL to the website manifest if you want to install it from CLI (for example, `firefoxpwa site install twitter.com/manifest.json`). However, [notion.so](https://www.notion.so) does not have a PWA manifest so you will have to install it from extension.
> 
> > When I try installing site with extension, it result in another error:
> 
> And here is the real problem and I'm not completely sure why exactly it happens. Can you please check [troubleshooting steps](https://github.com/filips123/FirefoxPWA/wiki/Troubleshooting) and provide full log file? Maybe it provides more details why it failed.
> 
> @TitanNano Can you please try to debug and fix this?
> 
> It seems the error happens [here](https://github.com/filips123/FirefoxPWA/blob/192c47495e7f99becf84d9d36b2a38b349feba79/native/src/integrations/macos.rs#L282-L284). Perhaps it could be related to [change in Homebrew formula](https://github.com/Homebrew/homebrew-core/commit/22860e8902e3350523fe9a259bd5e99e73b3f9b8#diff-f4ab72b7b727d1b4ca1a7b750ca0668113b43d8f1eadf98bf2cc59df5ba9187f) where I changed all paths to use unversioned paths (to fix #55), but I'm not sure why it would cause permission denied error.

new error:

```bash
$ firefoxpwa site install https://twitter.com/manifest.json  
16:15:00 [INFO] Installing the site
16:15:00 [INFO] Downloading the PWA manifest
16:15:01 [INFO] Parsing the PWA manifest
16:15:01 [INFO] Installing system integration
16:15:01 [ERROR] Failed to install system integration

Caused by:
    0: Failed to create application entry
    1: Failed to create application directory
    2: Permission denied (os error 13)
```
How to debug?

**Comment by filips123** [comment] 2021-09-13 17:16
Unfortunately, I don't know as I don't have much experience with macOS. It seems FirefoxPWA cannot create directory in `~/Applications/Site Name.app` because it doesn't have permission to do that. But I think `~/Applications` is a user-writable directory, so FirefoxPWA should have that permission...

You can check which permissions does `~/Applications` have. I think you can write `ls -al ~/Applications` in Terminal, and check in the first line who is the owner (it should be something like `drwxr-x--- 24 user user  4096 sep 13 18:57 .` where `user` is your username).

If all permissions are correct, maybe the problem is that Homebrew executes programs as its own user, so [`directories::BaseDirs::new()?.home_dir()`](https://github.com/filips123/FirefoxPWA/blob/192c47495e7f99becf84d9d36b2a38b349feba79/native/src/integrations/macos.rs#L218-L221) returns the wrong directory? I don't know how to check this (without editing and recompiling the program), and it still doesn't explain why writing failed.

Please also try to run `sudo dtruss firefoxpwa site install https://twitter.com/manifest.json` (or some other strace-like macOS program) to check all system calls that FirefoxPWA does. Note that this will probably output quite a lot of things, you you should probably save them to file using `sudo dtruss firefoxpwa site install https://twitter.com/manifest.json > firefoxpwa-dtruss.log 2>&1` and upload that file.

**Comment by TitanNano** [comment] 2021-09-13 20:45
@filips123 yes looks like there is no permission for writing to `~/Applications` which is really odd. By default, Homebrew always uses the current user, no superuser or dedicated Homebrew user.

**Comment by yangchuansheng** [comment] 2021-09-14 02:56
@TitanNano @filips123 The owner of `~/Applications` is root:

```bash
$ ls -al ~|grep Applications
drwxr-xr-x     6 root  staff      192 Sep 14 09:55 Applications
```
I didn't know why，but I solved the problem by giving write permission to `~/Applications`:

```bash
$ sudo chmod -R a+w ~/Applications
```

**Comment by TitanNano** [comment] 2021-09-14 19:25
@yangchuansheng this is very odd on macOS... `~/Applications` should be owned by your user as it is inside your home directory.

**Comment by filips123** [comment] 2021-12-26 11:50
I'll close this issue as there's not much I can do with it. I don't know why this happened, but if someone has the same problem, try to set write permissions to `~/Applications` directory:

```bash
$ sudo chmod -R a+w ~/Applications
```

If someone knows why this happens, please leave a comment and I'll try to fix it.

**Closed by filips123** 2021-12-26 11:50 UTC
Labels: bug
