### ISSUE TITLE
Can't pin PWA apps to taskbar after update

### ISSUE THREAD

**Issue by Sayayaya** [filips123/PWAsForFirefox#478] opened 2024-03-20 22:34 UTC
### Description

Can't pin PWA apps to taskbar. They won't open.

### Steps to Reproduce

1. Install the latest update 2.11.1
2. Launch a PWA site.
3. Right click in task bar. Pin to task bar.
4. Attempt to open PWA from taskbar.

Expected Behaviour:
PWA App opens from Taskbar. It did before the update.

Actual Behaviour
![image](https://github.com/filips123/PWAsForFirefox/assets/18683155/5776e1c9-f338-406d-9125-8c41acf7dd47)

### Environment

Windows 10

**Comment by filips123** [comment] 2024-03-22 15:00
First, update your antivirus definitions. Microsoft Defender detected version 2.11.1 as malware for some reason, so maybe it removed the files. Updating the antivirus definitions should remove the detection.

Then, try to uninstall the current PWAsForFirefox version from control panel or settings and reinstall it again. You may then also need to run "Update web apps" and "Patch profiles and runtime" from the extension settings.

**Comment by filips123** [comment] 2024-04-28 11:04
Were you able to fix the issue?

**Comment by filips123** [comment] 2024-09-13 16:19
I will close this issue as it was probably caused by Microsoft Defender. If you still have the issue, reinstall PWAsForFirefox and run "Update web apps" from the extension settings.

**Closed by filips123** 2024-09-13 16:19 UTC
Labels: bug, question
